### ISSUE TITLE
initialize deviceSelection

### ISSUE THREAD

**Issue by mrezzonico** [ericblade/quagga2#110]
Hi all,

I am working with _live_w_locator.js_
I am trying (without success) to initialize the select list _deviceSelection_ to (for example) the last option.

First solution
--------------
In the file _live_w_locator.js_ there is the following structure.

      constraints: {
         deviceId: getdeviceId(),
         width: {min: 640},
         height: {min: 480},
         facingMode: "environment",
         aspectRatio: {min: 1, max: 2}
      }

I added the line _**deviceId: getdeviceId()**_ and I wrote the function _getdeviceId()_.
In _getdeviceId()_ I find the last deviceId with the function _navigator.mediaDevices.enumerateDevices()_.
It works, but the big problem (for me) is that this function is aysnchronous and therefore I cannot return the value of deviceId.

Second solution
-----------------
I tried to initialize the select list with the following code:

      $(function() {
         setTimeout(function(){
            $('#deviceSelection').prop("selectedIndex",2);
            $('#deviceSelection').trigger('change');
         }, 5000);
      });

... without success.

Thanks for any help
Miche

**Comment by ericblade** [comment]
Hi! I completely missed seeing this issue posted, my apologies.

As enumerateDevices is asynchronous, you cannot call init with a parameter you need from enumerateDevices(), before enumerateDevices() has completed.   

What I do in my personal application, is I fire the asynchronous enumerateDevices() (which you can access via Quagga.CameraAccess.enumerateVideoDevices() for a consistent interface that only returns videoinputs, if you'd like) immediately upon application load, so it's ready long before the user ever gets to the point where they can pick what device to use.  If they manage to press the "camera" button before they have selected which camera to use, then we default to whatever facingMode: environment gives us, rather than using a deviceId.    Once the asynchronous response is received, I store that data somewhere for filling into the Settings page of the app, where there is a select drop down that can select which camera device to use.  

Once the user has selected a specific camera id from the settings page of the application, then i remember that choice, and can fill it in without waiting for the results of enumerateDevices().
