### ISSUE TITLE
Who has a modern iOS device that can test for iOS issues?

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#19]
One of the things that we routinely saw a ton of on the other repo was people having issues with iOS.  Unfortunately, the only iOS device I have is an iPad mini 2, which will not receive a version of iOS that provides getUserMedia . . . so I am completely useless on helping to track down any issues, or write any workarounds, or really provide any help at all with iOS.

**Comment by TomasHubelbauer** [comment]
Hey Eric, I have an iPhone 10 that I can test things on. Just mention me in an issue with repro steps any time you need something and I'll get back to you when I can.

**Comment by DanielTurner** [comment]
@ericblade 
I know it doesn't give you all the functionality but to test other parts if you haven't already you could look at:
https://www.browserstack.com/open-source

**Comment by ericblade** [comment]
fwiw, my fam now has access to a modern iPad, and I can probably use that to test my app that includes quagga.  it's not something i have ability to do hardcore dev work with though.

**Comment by ericblade** [comment]
hey @TomasHubelbauer if you're still out here, or anyone else who might be interested -- someone just filed a report against the original repo, that iOS is not able to read strings larger than 12 chars from a decode?  Anyone able to give that a test?

**Comment by TomasHubelbauer** [comment]
@ericblade I'm still around and able to test. Can you give me steps on how to test?

**Comment by ericblade** [comment]
![barcode (1)](https://user-images.githubusercontent.com/1451847/96759545-32a36500-13a6-11eb-8eac-e9b587d84ffe.gif)

my guess would be to scan this (it's Code-39) and see if all 20 digits comes out .. ? the original bug report isn't exactly full of details.   https://github.com/serratus/quaggaJS/issues/441

**Comment by TomasHubelbauer** [comment]
I have actually ended up using QR code in the app I eventually wanted to use Quagga for, that's why I'm so silent - I don't really use Quagga anymore, I'm just rooting for it's future because I think it should exist and that's why I stick around. :-)

I tried Serratus' live stream example on the GitHub Pages hosted site, but something is wrong with its CSS, the camera viewfinder element is like 25x the screen size, I see the individual pixels of it... I'll see if I manage to fix the CSS and then will try scanning.

**Comment by TomasHubelbauer** [comment]
I've found the issue: something is wrong with the code that requests the video stream, because it ends up getting a stream which is like 4x320 in size or something crazy like that. I've forked this repo and installed deps, but I'm not sure how to build and serve the examples, can you help me out?

I tried running `npm run build` to ensure it builds okay, then using `npx serve .` to serve the examples at http://localhost:5000 and then using `ssh -R 443:localhost:5000 ssh.localhost.run` to have a tunnel to my localhost with HTTPS which I could use on my phone. However the link returned by `localhost.run` says too many redirects, the browser fails to load it. Not sure what's that about, I contacted localhost.run to find out.

Do you know how to run the examples locally with HTTPS so that I can also access the local IP with my phone and have the TLS work? Without it, getUserMedia will not work. I figured in the worst case I could just fork, use GitHub Pages and push changes as needed and then use the GitHub Pages site to check, but that would be time consuming so I'm asking first if there's a better way.

**Comment by TomasHubelbauer** [comment]
Spoke too soon, I made a mistake, the correct command is `ssh -R 80:localhost:5000 ssh.localhost.run` and the returned URL can be readily accessed with HTTPS, too. I served the live stream example and pointed the camera at the image above and it got recognized without a problem:

![image](https://user-images.githubusercontent.com/6831144/96772521-884a3280-13e3-11eb-963f-28fe49e85cdf.png)

**Comment by TomasHubelbauer** [comment]
![image](https://user-images.githubusercontent.com/6831144/96773456-d27fe380-13e4-11eb-8c27-dc300dc69d90.png)

Took a steady hand and a bit of time... But it did scan eventually. :-) Also I had to go to landscape mode, but it might still scan in portrait mode, it probably just requires getting the alignment just right. I tried generating Code 39 barcodes with increasing number of digits using https://barcode.tec-it.com/en/Code39FullASCII and it started struggling after 12 digit numbers.

**Comment by ericblade** [comment]
Thanks for checking!

So, I'm not sure exactly what you're saying -- it looks like from the screenshots it is working, but it has issues after 12 digits?  Or are you saying the generator has issues after 12 digits?

**Comment by TomasHubelbauer** [comment]
The scanner is working up until 18 digits and was able to scan the picture in this thread. Using the online Code 39 generator, after 12 digits you have to focus on aligning the camera just right more and more. Up until 12 digits you pretty much just the to get the code into frame. With more, you really want to get the code horizontal, camera in landscape orientation and get the code as wide as the frame excepting some margin so that the left most and right most code bars do not touch the  edge of the frame. But the scanner is definitely working, even if it is not effortless to scan.

**Comment by ericblade** [comment]
Thank you!
