### ISSUE TITLE
How is the aspectRatio parameter working

### ISSUE THREAD

**Issue by fleflochN** [ericblade/quagga2#227]
Not a bug but I can't find anywhere (nor in the code) what the aspectRatio parameter is doing.
I would have understand if the values could be 16/9 or 4/3, but what des these 1 to 100 values represent?
It seems that it handle changes in the canvas size but I can't figure out whats the pattern.

Could someone give a a clue?

Thanks.

**Comment by ericblade** [comment]
Good question!

The aspectRatio parameter is part of the browser's MediaTrackConstraints object -- MDN doc is here https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/aspectRatio

Basically, it's the width divided by the height.  

You can specify a direct resolution (or range of resolutions) to choose using the width and height parameters, or you can specify an aspect ratio (or range of ratios) if you don't care about what resolution it is, only that it matches the desired ratio   (example, 640x480 and 1024x768 both have the same 1.333 ratio, if you specify a ratio of 1.333, you'll probably get the highest resolution device that is close to that ratio)

**Comment by fleflochN** [comment]
Hey Eric,

thank you for taking time to answer.
So if I understand correctly if I want to handle a classic smartphone camera (which will be 1920/1080) I will have to define my aspectRatio to 1.777.
But what about these values (min / max) from 1 to 100? I can't think about a camera which will have an aspect ratio of 100. Are they predefined aspectRatio we could use and if so where can we see them?

**Comment by ericblade** [comment]
I'm not sure exactly how to answer.  The MediaConstraint is there to help the Browser's getUserMedia figure out which devices are useful for the task you request.  You don't have to use aspectRatio, although that might help you get a camera that is both rear-facing and not wide-angle automatically.  

... this makes me wonder if I can specify a constraints object to pass to enumerateDevices(), since I think it's more useful to be able to select the camera device outside of Quagga, and then just pass Quagga a deviceId constraint.  

Anyway, you might want to read up on MDN on how constraints work https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

I'd think if you're primarily interacting with a smartphone display, you'll probably want to use either 16/9 or 4/3 if you're not full screen..  16/10 can be pretty common on PCs..   Interesting reading on common Aspect Ratios https://en.wikipedia.org/wiki/Display_aspect_ratio

You can just use like ```{ aspectRatio: 16/9 }``` i don't think there's a need for constants there

**Comment by fleflochN** [comment]
Hey Eric,
really detailed answer.
Thanks for helping !
