### ISSUE TITLE
iPhone Google Chrome - Error: enumeratedDevices is not defined

### ISSUE THREAD

**Issue by ricocynthia** [ericblade/quagga2#256]
Hello!

I am calling `Quagga.CameraAccess.enumerateVideoDevices()` in my app, and when iPhones try to use the scanner using Chrome there is an error being thrown `Uncaught (in promise): Error: enumerateDevices is not defined`.

Does anyone know a way to navigate around this error? Does Chrome not support this on iPhones? Or could this be some setting on the iPhones that is causing this error?

**Comment by ericblade** [comment]
On iOS, Chrome (and all other browsers) use an OS level WebView component, which is not presently allowed access to the getUserMedia and other related APIs, so it cannot be made to work, until/unless Apple changes their policies to allow other browser engines, or they enable getUserMedia and friends in WebView.

That said, there should be an error thrown here, rather than hitting the enumerateDevices is not defined.
