### ISSUE TITLE
Quagga not working anymore on Galaxy S10 / Android 10 / Chrome 86.0.4240.198

### ISSUE THREAD

**Issue by suzukieng** [ericblade/quagga2#276]
Quagga seems not to suddenly no longer work on the Galaxy S10, running latest Android 10 (QP1A.190711.020) and Chrome 86.0.4240.198 (seems like this could be the likely culprit).

`Quaga.init` completes successfully, the video stream is displayed, but no codes can be scanned. All I see in the log is an `Invalid asm.js: unexpected token` error message in the console, which I know from other projects is mostly harmless.

<img width="1247" alt="Screenshot 2020-11-12 at 19 16 21" src="https://user-images.githubusercontent.com/3542048/98979394-99d2b600-251b-11eb-8cd6-5e8ee04435d4.png">

I tried with the latest 1.2.6 release, and tried also downgrading to 1.2.5, neither of which helped.

Any advice on how to debug this?

**Comment by ericblade** [comment]
I have Chrome 86.0.4240.185 on Android 9, and everything seems to be working fine for me.  Blaming it on Android or Chrome seems a bit crazy at first, but, we do have a confirmed problem in Android 11 with the most recent Chrome https://github.com/ericblade/quagga2/issues/266 and the person at the tail end of this https://github.com/serratus/quaggaJS/issues/161 also indicates that going back a version of Chrome fixed whatever their issue was. 

I've noticed the invalid asm a lot recently, and i'm wondering if webpack is doing something that damages the asm.js section, or if it's literally been broken the entire time since the fork.  Invalid asm though will just run as regular javascript, and i'm not sure if chrome even really supports the asm feature.  so it shouldn't be the problem either.

With zero code errors showing up in your console, i'm not getting much of any ideas there.  If it's displaying the stream, I'd expect at some point, you'd get it to trigger onDetected somewhere.  

My first thought to see if it's actually doing *anything* would be to set a breakpoint somewhere in Quagga, and see if it's doing anything at all.  I'm not sure right off where a good point to do that would be, and it does look like you've got some custom webpack or similar work going on in there that i wouldn't be able to easily advise on.

You might also try registering a onProcessed handler if you're not using one currently, and see if that's being called.  That should be called every frame.

**Comment by ericblade** [comment]
@suzukieng please respond, i'm trying to clean up these repos :-) thanks!

**Comment by suzukieng** [comment]
Hi @ericblade. Sorry, i was too to try out your suggestions. Will do so in the next couple of days. Please leave it open, I will get back to you as soon as I can.

**Comment by suzukieng** [comment]
Hi @ericblade.

The `onProcessed` callback is being called, and frequently. So it looks like Quagga is processing frames. I have removed my `area` restriction in the init call, but that didn't do anything. I'm using only the `code_128_reader` with `multiple` set to false, code location is disabled as well. I am integrating Quagga in an Angular app, hence the webpack bundling.

Interestingly, the exact same code works just fine on a Galaxy A8, running the same version of Chrome, but on Android 9.

What is also noteworthy is that I have some code that determines if the 'torch' capability is present. This fails too on the S10, and works as intended on the A8. Specifically, the method below returns false because `capabilitites.torch` is falsy.

<img width="834" alt="Screenshot 2020-11-24 at 16 44 15" src="https://user-images.githubusercontent.com/3542048/100116687-53168180-2e74-11eb-941d-c64e7a12921c.png">

Am I for some reason running in a crippled environment? I am thinking of performing a factory reset of the device.

**Comment by ericblade** [comment]
This leads me to think of one of my first experiences with my LG G6 -- on my G6 there are multiple cameras, one of which is a wide-angle lens, which doesn't work at all to try to locate barcodes with, because everything is fish-eyed.  

Before just resetting everything, I would check to see if there are any other logical camera devices with Quagga.CameraAccess.enumerateVideoDevices and try those out to see if your results are any better?

**Comment by suzukieng** [comment]
Hi @ericblade 
Your comment brought me on the right track. Indeed the S10 has two back-facing cameras, and it seems that Quagga selects the "wrong" one. If I manually add contraints deviceId/groupId to select "camera2 0, facing back", everything works as expected.

<img width="1248" alt="Screenshot 2020-11-25 at 10 39 43" src="https://user-images.githubusercontent.com/3542048/100209870-a804d700-2f0a-11eb-97d8-751e4c21631f.png">

Any pointers on how to intelligently select a camera?

(by the way, have one on my, the PP donation from yesterday is for this ticket)

Kind Regards
Alex

**Comment by ericblade** [comment]
In my app, I currently just use a drop-down selector that I have the user tell me which one works.  I suspect that intelligently selecting would be down to providing some constraints to the quagga config object (and i have a note here somewhere that we need to be able to pass constraints to the enumerateVideoDevices function if possible)..  if you can figure out what the aspect ratio is for the wide-angle that we don't want to select, we could try to eliminate that range from the aspect { min, max } parameters in constraints.  I'd like to know the answer to that one too :-D  so we could provide that as a sane default, and it would catch more error cases.

and thank you so much for the contribution.  You might have no idea how much that is appreciated right now.

**Comment by suzukieng** [comment]
Yeah, I guess the problem is that enumerateDevices (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) does not support passing in constraints.

**Comment by ericblade** [comment]
ugh! i hadn't even looked up if that was possible, because i thought it was.  so, i guess there's not really any obvious way to make enumerateVideoDevices do that.  So I guess you're limited to either giving the user a choice, or providing something that resembles a sane default.  

So, I guess, the next question is... what's the aspect ratio of these wideangle setups?  if we can figure that one out, we can at least default the parameters better

**Comment by ericblade** [comment]
good news re: Asm.js error, sort of: asm.js error is basically a warning.  It just runs the code as javascript since it can't interpret it properly into what it's looking for.  bad news, although i can fix the one in this code, after i fix up several of them, i end up with one that the original author wrote which is also invalid, and i don't have any idea how to fix it, and information about asm.js is pretty sparse these days.
