### ISSUE TITLE
[QUESTION] Need help with a few questions

### ISSUE THREAD

**Issue by SudhamJayanthi** [ericblade/quagga2#280]
Hey everyone, 
This is my first time in this repo, I have a few questions and any help would be _highly appreciated_.
I want to use this library for a project I'm doing & would like to know:
1. What's the latest **stable** version I can download ?
2. Is this project still **actively** maintained ?
3. Would I face any issues if I use this in a **_Flask(python framework)_** web app ?
4. Would you recommend me to use [this repo](https://github.com/ericblade/quagga2/) over the [original quagga repo](https://github.com/serratus/quaggajs) ?
5. What all types of Bar Code types can be recognised using this ?
6. Is there a way  to automatically recognise any barcode type without selecting a specific type ?

_Thanks in advance ;)_

**Comment by ericblade** [comment]
1- I would consider the current version 1.2.6 to be quite stable, as it's being used in my project, which I use close to daily, however, I only use upc/ean scanners, so those are the only pieces that i routinely test beyond automated testing.

2- I'm a bit less active than I was at the beginning of the year, but I'm definitely still here :-) 

3- I don't know anything about Flask, but it looks to be more like the server side of an application, rather than the client side.  If you're trying to run quagga inside the web app, i don't see any reason why Flask would be an issue, you'd just need to make sure the browser loads the quagga script from somewhere, and runs it

4- Generally, yes -- there are some bugs fixed, some performance improvements, a lot of restructuring of code, and significant upgrades to the support libraries, as well as a few new features

5- basic codes supported are (from the README)

![image](https://user-images.githubusercontent.com/1451847/99702494-d8102e00-2a63-11eb-8ba1-68eb8e3e5719.png)

and some of the readers support some extensions to those types

   a) A new function of this fork, is the ability to add additional decoders.  There's an experimental QR reader, although since QR is vastly different from regular barcodes, it doesn't really use any of the functionality of Quagga, Quagga just passes the image down to the QR reader, which passes it to an external QR reader library.  It should be possible, though, to plugin new 2D barcode decoders as well, although I haven't built any new ones.  
   b) code_32 is a recently contributed reader from one of the users here, but it was added to the main codebase while I was still working on the external plugins functionality.

6- while it is *possible* to just tell it to use all of the decoders, and that will sort of have the effect of automatically recognising any type it supports, you're going to run into some issues with that 

   a) performance -- running detection on many readers at once takes a LOT of cpu time, which if you're using things like handheld devices, can definitely cause a noticeable slowdown in performance and battery
   b) false positives -- as some barcodes are subsets or supersets of other barcodes, and nearly all of them use very similar encoding, the more readers you enable, the higher the chances are that one reader will find a barcode of one type, but it's actually a barcode of a different type
   c) even when you do have a small subset of decoders to use, sometimes they can still get in the way of each other -- i want to say that EAN and UPC are so similar, that you must specify one before the other, or the other one will pick up first, and you'll always get the wrong code when scanning the latter one, because the first reader picks it up 100% of the time.  I may be wrong about which readers those are, though.

**Comment by SudhamJayanthi** [comment]
Hi @ericblade, thanks for the fast & detailed reply!
I want to use this in a web project using a script tag, but I could neither find the quagga.js file/dist folder in this repo! Could please drop a link to quagga.min.js ?

**Comment by ericblade** [comment]
either use npm install to install the package and copy it from that, or clone this repository and use npm install then npm run build to generate

**Comment by SudhamJayanthi** [comment]
> either use npm install to install the package and copy it from that, or clone this repository and use npm install then npm run build to generate

@ericblade Yeah! I had built it and copied it. I have also generated CDN links using [JS Delivr](https://www.jsdelivr.com/) & made a pull request for others to use it in the future. You can review it here #282 and make any changes if any necessary!

Thanks again for the help and quick replies!

**Comment by ericblade** [comment]
oh, cool. i hadn't realized it was that easy to get a cdn to host something.  nice.  thank you!
