### ISSUE TITLE
node-test example not working well

### ISSUE THREAD

**Issue by pguardiario** [ericblade/quagga2#314]
When I run the node-test script I see it works for test/fixtures/code_128/image-001.jpg, but it only gets 3 out of the 10 in that folder, and it crashes on some of them. Is this expected behavior or am I doing something wrong?

**Comment by ericblade** [comment]
I'm so glad someone is running tests! :-D  I've spent a LOT of effort on upgrading the test suite from what we had originally when forked! :-D

It is known that several tests fail, it is my hope that we will maybe perhaps have some people working on improving image recognition, and getting any of the tests that are currently failing without also breaking any of the ones that are working would be a great place to start :)

All of the tests that are failing now were also failing when I forked the code, although 2 tests that were failing before have started passing since then, so there's been some improvement (i believe they were in the code39 reader, so not too helpful for a lot of us, i think most people are using ean/upc/code128).  

Right now when any changes are made, I compare the test results to previous test runs, and as long as the number of failing tests doesn't go UP then i'm happy.

Does that answer your question ?

**Comment by pguardiario** [comment]
Kind of, I was wondering if those images were being recognized correctly
elsewhere and just not by the node-test.js script.

**Comment by ericblade** [comment]
i really haven't tried them in any other configurations.  my assumption is that a few of them might be picked up with some adjustments to the configuration, but it wouldn't surprise me if there's not enough whitespace around them for several.  i just haven't really concentrated on trying to improve the actual detection and decoding codes at all, i've spent the entire time since forking just modernizing the code and getting it to work reasonably with typescript.
