### ISSUE TITLE
Difference from original

### ISSUE THREAD

**Issue by GlauberF** [ericblade/quagga2#326]
What is the difference between this library and the original?

**Comment by ericblade** [comment]
Going to move this over to the Discussions :-) 

Thanks for the question!

Functionally, not a whole lot -- it adds the ability to use externally written readers, fixes some bugs here or there.  Multi-threading/WebWorker support has been removed.   As far as I know, the only external reader at the moment is a QR decoder, which you can find at http://www.github.com/ericblade/quagga2-qr-reader  .  I have an intent to make a OCR decoder plugin as well, but I think I might get to doing a lot of code separation work before I actually implement that, unless I decide my app needs it sooner rather than later. :-D  

Internally, a lot of it is now in TypeScript, nearly all the dependencies have been updated to modern releases, and the automated test framework has been completely revamped to use a different engine and hopefully tests everything in both node and browser.

I started to write a proposal describing some of the restructuring I'd like to do in the future https://github.com/ericblade/quagga2/discussions/323
