### ISSUE TITLE
Not detecting barcodes without successful scan

### ISSUE THREAD

**Issue by myrjola** [ericblade/quagga2#45]
Thank you for taking over maintainership of this package!

I noticed the live_w_locator example has changed behavior between versions 0.0.2 and 0.0.3. Earlier, the scanner was painting green squares when it started noticing barcodes without successfully scanning them, i.e., `onDetected` callback is not called. Now, the green squares are only painted when a barcode is successfully scanned. So it seems the content of `result.boxes` for the `Quagga.onProcessed` callback behaves differently after version 0.0.3. Is this a regression?

To reproduce

* Compare the old behavior on https://serratus.github.io/quaggaJS/examples/live_w_locator.html to the live_w_locator example in master branch

**Comment by ericblade** [comment]
Oof, thanks for noticing that.  I'll try to run that locally and see if I can figure out the difference there -- if it's broken, it wasn't intentional.  .3 is to support adding a new feature to add external decoders, so there's no reason not to go back to .2 if that fixes the problem.  I haven't quite nailed that down perfectly, yet, though.  

It's a bit of a tough one, because none of my USB webcams even show any boxes on the original quagga, they're just not good enough for the recognition to trigger anything at all.  SO I need to test the live stuff using my phone. 

Any chance you might be able to check and see if it's a drawing issue or is onDetected not being called at all?  I'm hoping to get back into Quagga soon, I was just undergoing a major re-build of the app that I am working on that uses it. :-)

**Comment by myrjola** [comment]
I think it's an issue with `onProcessed`. During my testing yesterday, the `result.boxes` was empty until a barcode was scanned, i.e., `result.codeResult` was set. So I only see the boxes when a barcode is scanned succesfully, otherwise no boxes are shown.

**Comment by ericblade** [comment]
hmm.  There's some difference here, in that previously quagga::publishResult() was called with no parameters, when a barcode was not decoded.. publishResult with no parameters would call Events.publish('processed') with an undefined parameter.. i thought removing that would just eliminate unnecessary empty processed events... but apparently it breaks something.  This is fairly complex software, which I was hesitant to modify for a while because of things exactly like this, where seemingly small changes could have large sweeping effects if not understood 100% :-D

**Comment by ericblade** [comment]
@myrjola Martin, if you could test this commit before I get setup to do so, please let me know if that solves? https://github.com/ericblade/quagga2/pull/46

It should restore the old code path for when there's no external image readers registered, so I think it should fix it.. although I still don't entirely grasp what the difference is -- at a glance, it looks like calling publishResult() and publishResult(null, _inputImageWrapper.data) should have very close to the same end result, but in practice that seems different than expected.

**Comment by myrjola** [comment]
Thanks for looking into this! Sadly, it didn't work.

**Comment by ericblade** [comment]
hmm. ok. it'll take me a bit to get to a point where i can debug live on my phone..

**Comment by ericblade** [comment]
Confirming that onProcessed in 0.0.2 gets an object that contains one field called boxes, which looks like:

````
{ boxes: [ [x1, y1], [x2, y2], [x3, y3], [x4, y4] ] }
````
where x and y are, i'm guessing, the corners of the boxes.

onProcessed in 0.0.5 is receiving an empty array.

Recommend pinning to 0.0.2 until this is fixed.

**Comment by ericblade** [comment]
Lessons learned today:

1. my computer's webcam does in fact work well enough to at least recognize boxes
2. npm link + webpack dev server are an amazing combination
3. fixing what appear to be tiny lint errors may introduce a change to a function that has sweeping effects on the rest of the software, so don't even think about changing a return value until you have a complete understanding of where that return value might be used.   (somewhere in the result handling, someone is expecting decodeFromBoundingBoxes to return undefined, which in the code inherited, was not an explicit return, so i fixed the function to always return a value, but that's not correct.)

0.0.6 should fix this issue

**Comment by myrjola** [comment]
Thank you Erik for the fix! I can confirm that it works.
