### ISSUE TITLE
Unable to add torch button on the qugga2 library

### ISSUE THREAD

**Issue by Hrithik31** [ericblade/quagga2#496]
Hi @ericblade,
I'm trying to add a torch button for ease of scanning the barcode in dark conditions but am unable to add it as I'm not able to get how do I integrate the navigator function into the quagga library in-build function or in the quagga init function. As I read the doc with the link but was unable to get the location of where the function needs to be placed.

Can you help me with this problem? If possible please share an example or Code-sandbox

**Comment by ericblade** [comment]
i use this in a React component

```
    const [bTorchOn, setTorch] = React.useState(false);
    const onSound = useAppSoundClickOn();
    const offSound = useAppSoundClickOff();
    const onTorchClick = useCallback(() => {
        const bTorch = !bTorchOn;
        setTorch(bTorch);
        if (bTorch) {
            // @ts-ignore
            Quagga.CameraAccess.enableTorch();
            onSound();
        } else {
            // @ts-ignore
            Quagga.CameraAccess.disableTorch();
            offSound();
        }
    }, [bTorchOn, setTorch, onSound, offSound]);
```

Quagga.CameraAccess.enableTorch() and disableTorch() should work in recent quagga2 releases, though I don't know if there's any way on device to query if the camera is on  (probably there is, i've never tried) so i just keep track of the state it should be in

**Comment by ericblade** [comment]
Does that help?

**Comment by Hrithik31** [comment]
HI @ericblade, Thank you for your response, Actually I just saw your answer, I have a question about the **useAppSoundClickOn** hook are you using any external npm package because I'm trying to implement it into a web application based on the next JS 12, and this above function to be called in the quagga. init method after the constraints are defined, right?

**Comment by ericblade** [comment]
The sound thing is just part of my app, i play a little 'click' noise when the button to turn it on is clicked.  I don't know what structure you've got, or what frameworks you're using, but basically you need to call enableTorch() when turning it on, and disableTorch() to turn it off

**Comment by Hrithik31** [comment]
HI @ericblade, I got to turn on the torch but could not turn it off, and I observed that the barcodes on the screen were detected more quickly than the barcodes on the box.

can you please help me out with this problem?

**Comment by ericblade** [comment]
displays tend to be much brighter and easier to read, I'd guess that's probably normal, though I haven't done a lot of scanning of computer displays, i usually use it on UPCs on packages.  I don't think I can advise much there, other than make sure there's plenty of whitespace around the barcodes, if possible.  If I have trouble with it locating a barcode, due to things around the barcode, i can usually lay a finger, or a sheet of paper above or below the barcode and have it find it.  Adjusting some of the patch size parameters and resolution settings may also improve detection.   Or simply using the "area" parameter to define a specific detection area, if location is a problem.

As far as not disabling the torch, I know for a fact the function works, as I use it in my own application frequently, so I would suggest debugging into your application to figure out why it's not hitting disableTorch.  If it is clearly hitting disableTorch but it's not actually disabling, then we can try to debug further

**Comment by Hrithik31** [comment]
HI @ericblade, I tried the solution for the diableTorch but it didn't work, It didn't work for the web demo, the enableTorch function was working but the disableTorch didn't work. 

I even tried cloning the React example that is shared in the read me, I've compared the React setup with the given example, and yet I'm unable to disableTorch nor are the images being scanned.

I've another question, is the link:- [serratus/quaggaJs](https://github.com/serratus/quaggaJS)
Is this code already merged within your project, or is it a different project?

Can you please help me out figuring out what's going on with the React setup, or implementation in React?

**Comment by ericblade** [comment]
Torch support added to sample application.  Works for me.  Please let me know if it does not for others.

https://github.com/ericblade/quagga2-react-example/blob/master/src/App.js
