### ISSUE TITLE
Code128Reader properties should be changeable via Quagga Configuration

### ISSUE THREAD

**Issue by jogibear9988** [ericblade/quagga2#71]
For Example:
AVG_CODE_ERROR

**Comment by ericblade** [comment]
Hi @jogibear9988 could you please provide a more explicit description of what you're looking for?

Thanks!

**Comment by jogibear9988** [comment]
for example this: https://github.com/ericblade/quagga2/blob/99726f07d25be7b3d4a7fa880378be41e8de9426/src/reader/code_128_reader.ts#L122
i'd like to change the value via configuration

**Comment by ericblade** [comment]
hmm. i don't recall ever seeing this issue, otherwise i would've said something on it.  On it's face, this seems like a pretty reasonable request, but I'm not entirely certain what the purpose of that is right off hand, if it's used, or how much  of a change it would entail to be able to do that.

**Comment by ericblade** [comment]
I know it's been a long time since we've visited this issue, but I believe it should be pretty easily targetable in the 2.x release, as I think we'll probably be passing already instantiated BarcodeReader objects around, so you would be able to configure it as you desire at that time.

You can do this in the 1.x branch, however, by creating a new BarcodeReader class that extends the existing one, and overrides the AVG_CODE_ERROR value, then supplying your new reader in the setup.

**Comment by ericblade** [comment]
closing this as I believe we have an acceptable workaround for the current release, and future design should address it further.  Please let me know if that is not the case, and re-open
